# Generated by Django 4.2 on 2023-05-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rdesc', models.TextField(default='')),
                ('rimg', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
