# Generated by Django 4.2 on 2023-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rimg',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
